### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by Gr1dd** [adjoint-io/nanochain#1]
Man this thing is like trying to fry chicken on a friday night without everyone eating it before it's done.

I admire how well you are at coding haskell.

**Comment by Gr1dd** [comment]
I just threw a binfo field on my fork :) man that was a task!! This haskell stuff.... brother...... This has to be one of the hardest languages to learn. But I want to add a /account field to the url get request that way you can mine to an account. Then the account name/number will be hashed and calculated with the rest of this stuff. This can actually add more entropy to hash faster.

**Comment by sdiehl** [comment]
Great, glad you found the code insightful.
